version: '3'
services:
  app:
    build: .
    ports:
      - "8001:8001"
    networks:
      app_net:
        ipv4_address: 213.18.0.30
        
networks:
  app_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 213.18.0.0/16
